// The synthetic series every Tier 2 spec plays: four still-image episodes
// (generated by `scripts/gen-syncplay-fixtures.mjs`), two translations per
// episode and two quality variants per translation — the minimum P6 / M6
// (translation switch) and P7 (quality switch) need (#489 review, edge cases).
//
// The translation-id → file map lives here and nowhere else: the fixture
// server resolves a request through `fixtureFor()`, and the handler swap in
// `duo.ts` builds `availableStreams` from the same ids, so the two cannot
// disagree about which file a translation plays.

import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { FIXTURE_DIR, GEN_FIXTURES_SCRIPT } from './paths'

export const ANIME_ID = 489_000
export const ANIME_NAME = 'Syncplay Fixture'
export const EPISODE_INTS = ['1', '2', '3', '4'] as const
export const HEIGHTS = [720, 360] as const
export const TRANSLATION_SLOTS = [
  { slot: 1, label: 'Fixture A' },
  { slot: 2, label: 'Fixture B' }
] as const

export interface FixtureTranslation {
  id: number
  label: string
  type: string
  height: number
}

export interface FixtureEpisode {
  id: number
  episodeInt: string
  episodeFull: string
  translations: FixtureTranslation[]
  downloadedTrIds: number[]
}

export const translationId = (episodeInt: string, slot: number): number =>
  1000 + Number(episodeInt) * 10 + slot

/** Which episode a translation id plays, or `null` for an id no fixture has. */
export function episodeOfTranslation(trId: number): string | null {
  for (const ep of EPISODE_INTS) {
    for (const t of TRANSLATION_SLOTS) if (translationId(ep, t.slot) === trId) return ep
  }
  return null
}

export function fixtureFile(
  episodeInt: string,
  height: number,
  container: 'mp4' | 'mkv' = 'mp4'
): string {
  return container === 'mkv'
    ? path.join(FIXTURE_DIR, `ep${episodeInt}.mkv`)
    : path.join(FIXTURE_DIR, `ep${episodeInt}-${height}.mp4`)
}

/** The request path the fixture server answers for one translation/quality. */
export const streamPath = (trId: number, height: number): string => `/tr/${trId}/${height}.mp4`

/** Inverse of `streamPath()`, resolved to a file on disk. */
export function fixtureFor(urlPath: string): string | null {
  const m = /^\/tr\/(\d+)\/(\d+)\.mp4$/.exec(urlPath)
  if (!m) return null
  const ep = episodeOfTranslation(Number(m[1]))
  const height = Number(m[2])
  if (!ep || !(HEIGHTS as readonly number[]).includes(height)) return null
  return fixtureFile(ep, height)
}

/** The `allEpisodes` payload PlayerView is opened with, so `getAnime` /
 *  `getEpisodesBatch` never reach the network (#489 review). */
export function allEpisodes(downloaded: number[] = []): FixtureEpisode[] {
  return EPISODE_INTS.map((ep, i) => ({
    id: 489_100 + i,
    episodeInt: ep,
    episodeFull: ep,
    translations: TRANSLATION_SLOTS.map((t) => ({
      id: translationId(ep, t.slot),
      label: t.label,
      type: 'subRu',
      height: HEIGHTS[0]
    })),
    downloadedTrIds: downloaded.filter((id) => episodeOfTranslation(id) === ep)
  }))
}

export interface Manifest {
  files: { name: string; episodeInt: string; height: number; durationS: number }[]
}

/** Generate the fixtures if they are missing (idempotent), then read the
 *  manifest. Setup, not assertion — so it is the one place a retry is fine. */
export function ensureFixtures(): Manifest {
  const manifest = path.join(FIXTURE_DIR, 'manifest.json')
  for (let attempt = 0; attempt < 2; attempt++) {
    const r = spawnSync(process.execPath, [GEN_FIXTURES_SCRIPT, FIXTURE_DIR], { stdio: 'inherit' })
    if (r.status === 0 && fs.existsSync(manifest)) break
  }
  return JSON.parse(fs.readFileSync(manifest, 'utf8')) as Manifest
}

export function durationOf(m: Manifest, episodeInt: string): number {
  const f = m.files.find((x) => x.episodeInt === episodeInt)
  if (!f) throw new Error(`no fixture for episode ${episodeInt}`)
  return f.durationS
}
